name: Routing Tests
on:
  push:
    branches:
      - routing

jobs:
  routing_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Start local server
        run: npm start
        background: true

      - name: Wait for server
        run: sleep 10

      - name: Run routing tests
        run: npm test
